[package]
name = "undetected-chromedriver"
version = "0.4.0"
edition = "2021"
description = "An undetected implementation of thirtyfour."
repository = "https://github.com/MustCodeAl/Rust-undetected-chromedriver"
license = "MIT"
readme = "README.md"
keywords = ["chromedriver", "selenium", "stealth", "automation", "webdriver"]
categories = ["web-programming", "development-tools::testing"]

[dependencies]
async-trait = "0.1"
base64       = "0.22"
rand         = "0.10"
reqwest      = { version = "0.13", features = ["json"] }
serde_json   = "1.0"
tempfile     = "3"
thiserror    = "2"
thirtyfour   = "0.36.*"
tokio        = { version = "1", features = ["full"] }
zip          = "8.2"